theme: minima
title: Jekyllito test blog dot com
author: Maria
email: maria@test.com
description: > # this means to ignore newlines until "baseurl:"
  Exploring jekyll and its goods. So far so good!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
